---
- name: Configure variables for role
  include_tasks: variables.yml

- name: Check to see if Nomad is already installed for upgrade purposes
  stat:
    path: /usr/local/bin/nomad
  register: nomad_upgrade

- name: Install Nomad
  include_tasks: install.yml

- name: Configure Nomad
  include_tasks: config.yml

- name: (Optional) Configure Vault settings for Nomad
  include_tasks: vault.yml
  when: nomad_vault_enabled

- name: (Optional) Configure consul-template for Nomad
  include_tasks: ctpl.yml
  when: nomad_ctpl_enabled

- name: Ensure Nomad is started and enabled
  systemd:
    daemon_reload: true
    name: nomad
    state: started
    enabled: true

- name: Restart consul-template@nomad
  systemd:
    daemon_reload: true
    name: consul-template@nomad
    state: restarted
    enabled: true
  when: nomad_ctpl_enabled
...
